language: java
sudo: false
install: true
addons:
  sonarqube:
    organization: dockhouse
    token:
      secure: QHNBJ5V3bQTUzproai82tBguvMBd0b7DHDks7ZM8PC8kQSB1KxdZhDTOAwZv78RxCZry6G4/71VlfdmiEBQqf7rVNYig/DF5DY/JNsdIIZM+YdfCltRVIHr1Iaje8kVU30gRbUOqKlAlB2r/rDGYq43oXBlyvCL2Q/MKAPqoGQ2+XcBYs5aLnN3xuifjrnxnZTTO7Zh8mCw2HS1Sjnz2kRKeAGdKeleVGxutiTDizD49kWYWGJgm/WmiB0U0L/qtrRkA4zOFdbwVDbFmPjRIszD+PXlFWvJkSVoxZhXD2x5SHi2xIPZQHxldu7sV//1lIG8GTugAgPUul4jWu5P9GiQyaEBBz51/n/jRY0pGIQiaFkx1saQ9dsNqy/NFCtHfgEo1/FEtS6SJPEwUq6RQ+UFnFJkWEtXcVpFOxdJaTJy1ZNbPiS3p4vIEIBpm0DqFIipdGZjjtpjDLvKp0E2xCwzRi3aLL4owswotPEunz14D4W8CrgbGykT11uNGbm0MK/nwyc9M77L6omFx8JmcFWuO5cyk1pydCHhQ++edHKb0+RM/5+5HNyNxVVyngxnWZ8oCanIW8eaGY5FN99QXtuylUfs6qYqt6mk5TQii4lCgZz0RAxht0V6l8wCZzNkYhhXKFAdLDr1O4pNhzeMINYffoVWVIBXHArorf6rbnFU=
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
notifications:
  email: false

env:
  global:
  - secure: EscPf1qnbOCCdz0D4eCu3RCllN/DKBJ3rdY/R8fClS+M3aA4ijLcF/Tv8bRc/UoAceQBhkK2M7EmTC1kSPJ8oPvDnIHhvYfmtgbi1BL6MB5QMJaXFismv3Nj1f48L7g3x1vDNY0biH95a1+9iuz52W6GGHVrF3h97lQqlPGTPtLoCnIeN3BjPBq/mpZRWkvelB1jd5h8GqPNOAhrVzU4UdLRlACMVn+0w9kK7mJS8DHExXd0Ko1r3lrs6fhB67ZAkE9fOaTXj1kFpIlQUq63QrDNxQRyINTkhRQ+yHkIDzMgcmoHxkSVINEkYSZ+6xii3mXaVZF0LT517uEUjeoW21QBtZ3Net6acC9oc7UHk3i5kBQ852KLDfRw26hP+AXdd9OIeKbucLedzJp22j4/PVnmYUGH5oFo1xNySmlZTZpA4UoWMMr1eAxyCQAAoJLUp4eb2CH+A3uSB9XHZHlgq4xfPgz+Zt5nOM0ghRfQFEqqp0ZPMBqi3BFj2WBv9BF97c3OePn8HUNlfQADFT5pk0gQpU0sbdqAjdgFeoJysEhHgGKbWRmoDDpUwReCR+jhX2eAe0vV28mqJ4ot9p2kQERDD8aZLl1zp3c19qHNTajPbSRa/vUo9vLSCEV/AGuX1qaPqTDwYI68N+PW9hJ+QGDXYMQQbTSBQ4E6Eu89eVw=

